### ISSUE TITLE
Sentry 슬랙 알림 내부인원 제외

### ISSUE THREAD

**Issue by sdkfile** [ACON3D/ABLER#36]
브랜치에 상관없이  저희 내부인원인 경우 (acon3d.com) 슬랙 알림이 오지 않는 방향으로 수정되면 좋을 것 같습니다!

**Comment by seungha-kim** [comment]
으어... 현재 에러 이벤트에 release 속성은 의도대로 잘 들어가고 있는데, 이걸로 필터링을 하려면 상위 프라이싱 플랜을 선택해야 하네요 흑흑.. 

![image](https://user-images.githubusercontent.com/767106/145158503-4383eb04-8c64-4c05-bba3-c364a5a2ca11.png)

environment 속성 등 다른 방법으로 필터링을 해야할 것 같습니다. 일단 현재 바깥에서 발생한 에러는 없는 것으로 보여서 슬랙 얼럿은 꺼둔 상태입니다.

**Comment by seungha-kim** [comment]
PR에 올라온 대로 environment 설정을 추가하면 아래 스크린샷처럼 바로 알림 설정이 가능합니다.
![image](https://user-images.githubusercontent.com/767106/148523641-964b182e-1573-497c-818e-e74e73e75df9.png)
