### ISSUE TITLE
.blend 파일 Import 시 같은 이름의 컬렉션이 이미 존재하는 경우 크래시

### ISSUE THREAD

**Issue by sdkfile** [ACON3D/ABLER#57]

**Comment by Youdiie** [comment]
![스크린샷 2022-01-25 오후 1 34 59](https://user-images.githubusercontent.com/87409148/150911989-1ceced6b-7518-4841-bbdf-4687be31ccc4.png)
1. import시 `Layers` 콜렉션과 `Imported` 콜렉션 두개에 각각 하위 콜렉션이 생기고 있음
2. layer0이란 레이어가 있는 .blend파일을 import하면 `Layers`-[layer0], `Imported`-[layers.001]-[layer0] 요렇게 하위로 콜렉션이 생김.
3. 이 파일을 .blend로 저장한뒤 새 파일에 import하면 [layers.001]도 가져오면서 이름이 겹쳐 컬렉션이 없는데도 이미 존재한다고 크래시가 발생!
