### ISSUE TITLE
모델 첫 오픈 시 라인이 굵어지는 현상 개선

### ISSUE THREAD

**Issue by sdkfile** [ACON3D/ABLER#59]
[https://acontainer.slack.com/archives/C029RU0E293/p1637923658056200](https://acontainer.slack.com/archives/C029RU0E293/p1637923658056200)

![image](https://user-images.githubusercontent.com/43770096/150291176-4fbcac9e-8e77-41f9-a9e8-6425b356f9c5.png)

→ 모델을 처음 오픈했을 때

![image](https://user-images.githubusercontent.com/43770096/150291232-f6ea24d3-8444-48bc-864b-ada1a88cead5.png)

→ 원래 모델

**Comment by Youdiie** [comment]
요거 애나님께 여쭤보니 파일 오픈하고 아무 레이어나 값 변경한뒤 다시 원래값으로 돌리면 라인굵기가 원래대로 돌아온다고 합니닷
