### ISSUE TITLE
마우스 오버시 기능 안내 추가 

### ISSUE THREAD

**Issue by sdkfile** [ACON3D/ABLER#64]
## 체크사항 (패널 기능 내)
1. 마우스 오버시 명칭이 나오는가
2. 마우스 오버시 기능 안내가 나오는가

**Comment by sdkfile** [comment]
# 기능 목록
## 일반
- 파일 열기  
설명: 파일 열기  
단축키: Ctrl O
- 가져오기  
설명: 현재 설정에 맞추어 모델을 가져옵니다.
- 언어  
번역에 사용된 언어: 한국어 (한국어)
ko_KR
- 툴바 열기 / 닫기  
설명: 툴바를 열거나 닫습니다.  
단축키: T
- 플라이 모드  
설명: Fly Mode.  
단축키: Shift ` 
## 씬
- 씬 전환  
설명: 씬을 전환합니다: 씬
- 새로운 씬  
설명: 현재 설정을 이용하여 새로운 씬을 만듭니다.
- 씬 제거  
설명: 선택된 씬을 이 프로젝트에서 제거합니다.
## 모서리 선 설정
- 만화 스타일  
설명: 만화스타일 모서리 표시하기 토글버튼
  - 선 굵기 (최소)  
  설명: 심도가 가장 낮은 선의 굵기를 조정합니다.
  - 선 굵기 (최대)  
  설명: 심도가 가장 높은 선의 굵기를 조정합니다.
  - 모서리 디테일  
  설명: 보여질 모서리의 양을 조정합니다 (권장: 1.2).
## 면 설정
- 텍스쳐  
설명: 면 재질 표시하기 토글 버튼.
- 셰이딩  
설명: 음영 표시하기 토글 버튼.
- 만화 스타일  
  설명: 만화스타일 면 표시하기 토글버튼.
  - 색 표현 수  
  설명: 만화스타일 음영 표현에 사용되는 색의 수를 조정합니다.
  - 밝기 1  
  설명: 음영 표현의 밝기를 조정합니다 (범위: 0 ~ 10).
  - 밝기 2  
  설명: 음영 표현의 밝기를 조정합니다 (범위: 0 ~ 10).
- 빛번짐 효과  
설명: 없음
  - 임계값  
  설명: 임계값이 작을수록 더 많이 번집니다.
  - 변곡점  
  설명: 임계값 전후의 값을 더 부드럽게 변화시킵니다.
  - 반경  
  설명: 빛번짐 효과가 퍼지는 거리를 조정합니다.
  - 색상  
  설명: 빛번짐 효과에 적용된 색상
  - 강도  
  설명: 빛번짐의 강도를 조정합니다.
  - 클램프  
  설명: 빛번짐 효과의 픽셀이 가질 수 있는 최대 강도 (0에서 비활성화).
- 오브젝트 재질
  - 그림자
  - 셰이딩
  - 모서리
## 오브젝트 설정
- 나만 바라보기 (설명 없음)
- 상태정보 사용하기 (설명 없음)
  - State Slider  
  설명: Move between begin and end of the state.
## 이미지 보정
- 밝기 / 대비
  - 밝기  
  설명: 전반적인 이미지의 밝기를 조정합니다 (범위: -1 ~ 1).
  - 대비  
  설명: 전반적인 이미지의 대비를 조정합니다 (범위: -1 ~ 1).
- 색상 균형
  - 레드  
  설명: 색상 밸런스를 조정합니다 (범위: 0 ~ 2).
  - 그린  
  설명: 색상 밸런스를 조정합니다 (범위: 0 ~ 2).
  - 블루  
  설명: 색상 밸런스를 조정합니다 (범위: 0 ~ 2).
- 색조 / 채도
  - 색조  
  설명: 색조를 조정합니다 (범위: 0 ~ 1).
  - 채도  
  설명: 채도를 조정합니다 (범위: 0 ~ 2).
## 그림자 / 빛 속성
- 햇빛
  - 강도  
  설명: 제곱미터당 와트수로 나타낸 태양의 강도 (W/m^2).
- 그림자
  - 고도
  설명: 그림자의 길이(태양의 고도)를 조정합니다.
  - 방위각  
  설명: 그림자의 방향(태양의 방위각)을 조정합니다.
## 카메라
- 플라이모드  
설명: Fly Mode.
- 초점의 길이  
설명: 초점의 길이를 조정합니다. 초점이 짧을수록 광각, 초점이 길수록 평행투영에 가까워집니다.
- 카메라
  - 카메라 추가  
  설명: (문서화되지 않은 작업자).
  - 카메라 제거  
  설명: (문서화되지 않은 작업자).
  - 피사계 심도 (DOF) (설명 없음)
    - 오브젝트에 초점  
    설명: 스포이드 버튼으로 선택한 오브젝트에 초점을 맞춥니다. 해제하려면 우측의 X표시를 눌러주세요.
    - 초점 거리  
    설명: 피사계 심도의 초점 거리.
    - 흐려짐 정도  
    설명: 흐려짐의 정도를 조정합니다. 낮을수록 흐려집니다.
  - 배경 이미지
    - 이미지 추가
      - 이미지 타입
      - 이미지 선택
      - 불투명도
      - 배치
      - 프레임 방식
      - 오프셋 X
      - 오프셋 Y
      - 회전
      - 스케일
      - 뒤집기
        - X
        - Y
## 레이어
- Layer Lock
- Layer Exclude
## 렌더
- 카메라 뷰
- 해상도 X
- 해상도 Y
- 빠른 렌더
- 고급 렌더
- 선 렌더
- 그림자 렌더
- 씬 연속 렌더
- 오려내기 렌더

**Comment by Youdiie** [comment]
2차 업데이트를 위해 열어두겠습니당
