### ISSUE TITLE
파일 저장 후에 새로 오픈시 최종 씬이 오픈되는 것이 아닌 Scene이 오픈됨

### ISSUE THREAD

**Issue by sdkfile** [ACON3D/ABLER#80]
- 재현 방법
1. 파일을 로드
2. Bloom이 켜져있는 상태로 패널이 로드됨
3. Bloom이 먹힌 상태로 로드되지 않음
4. Bloom 토글을 껐다가 켜면 Bloom이 적용됨

- 테스트한 파일
[09 University Dormitory_with_lights_13ver2.zip](https://github.com/ACON3D/ABLER/files/7940661/09.University.Dormitory_with_lights_13ver2.zip)

- use_bloom을 업데이트하는 Update function
https://github.com/ACON3D/ABLER/blob/31389948bd01dd3335eb0038d841504d4982bf66/release/scripts/startup/abler/lib/scenes.py#L47-L53

- 예상 해결방법
파일을 오픈할 때, 현재 prop.use_bloom 값을 받아와서 강제로 context.scene.eevee.use_bloom에 넣어주는 코드를 아래 부분에 넣어주면 될 것 같습니다.
https://github.com/ACON3D/ABLER/blob/31389948bd01dd3335eb0038d841504d4982bf66/release/scripts/startup/abler/lib/post_open.py#L13-L16

**Comment by Youdiie** [comment]
스듴님 요이슈 확인해보니까 bloom이 적용이 안되는게 아니라 파일오픈시에 [Scene]씬이 열려서 적용이 안된것처럼 보이는겁니다! 씬 패널에는 이전에 저장한 씬으로 표시되는데 실제로 보이는건 Scene입니다!
<img width="1418" alt="스크린샷 2022-01-27 오후 2 53 44" src="https://user-images.githubusercontent.com/87409148/151300843-ae8e3dfa-7900-4a01-9b00-aec710221f22.png">

**Comment by sdkfile** [comment]
파일 오픈 시에 Scene이 열리는 현상으로 제목 바꿨습니다 :) @Youdiie

**Comment by Youdiie** [comment]
요거 다른파일에서 확인해보니 Scene이 아닌 다른 씬으로 잘 열리네요.. 저파일만 왜저러지🤔

![스크린샷 2022-01-27 오후 8 43 25](https://user-images.githubusercontent.com/87409148/151352440-5ef0d43b-816d-4958-b236-d5289d4c4015.png)
그리고 bloom은 스듴님 올려주신 파일로 열어서 bloom 수정하고 저장해서 다시 열었더니 bloom이 잘 먹힌상태로 열립니다!

**Comment by Youdiie** [comment]
요 이슈 어떤현상인지 파악했습니다! 윈도우에서 더블클릭으로 파일을 열면 Scene구도로 보여지고, 코니방에서 File Open 버튼을 눌러서 열면 저장했을 때의 씬으로 열립니다! 아마 File Open 버튼에 추가된 내용이 더블클릭에서 적용이 안되는거 같습니닷!

**Comment by sdkfile** [comment]
https://github.com/ACON3D/ABLER/blob/fe9a189adba3954c67ab7a04e43ef38f2b4416e4/release/scripts/startup/abler/general.py#L179-L192

현재 File Open 버튼에서는 기본 오퍼레이터 이외에는 추가된 내용이 없는 것으로 보이는데 더블클릭과는 어떻게 차이가 있는지 잘 모르겠습니당 ㅠㅠ

**Comment by Youdiie** [comment]
요것두 C의 영역으로 들어가는군요.. 흑
file open버튼으로 열었을 때와 더블클릭으로 열었을 때의 로그에서 차이가 보입니다!
![image](https://user-images.githubusercontent.com/87409148/151492894-66045207-ddcd-4190-a302-70feeac380db.png)

관련된 코드는 요파일인거 같습니다
https://github.com/ACON3D/ABLER/blob/fe9a189adba3954c67ab7a04e43ef38f2b4416e4/source/blender/blenkernel/intern/blendfile.c#L737-L761

**Comment by Youdiie** [comment]
윈도우에서 더블클릭해서 열때 [Scene]이란 이름의 씬이 있을때만 무조건 [Scene]이 열리고, 없다면 저장한 씬이 열립니다!
해결책으로 기본값인 Scene을 삭제한 상태로 에이블러를 여는 방법도 있겠네요🥲

**Comment by Youdiie** [comment]
이게 단순히 윈도우에서 더블클릭할때 [Scene]으로 열리는게 아니네요. [Scene]이름의 씬의 패널값을 변경해서 저장하고 다른 씬으로 바꾼뒤에 다시 열면 변경된 패널값의 [Scene]이 아니라 저장한 씬의 패널값에 카메라만 [Scene]을 따라갑니다.. 도대체 먼 기준이지🥲

**Comment by Youdiie** [comment]
@sdkfile 
요내용도 3.0으로 업데이트되면서 어느정도 해결되는거 같습니다! 같은 파일을 열었을 때 오른쪽이 3.0, 왼쪽이 2.93인데 3.0에서  scene의 속성들이 제대로 반영돼서 열리는걸 확인할 수 있습니다!
(파일 더블클릭해서 열었을 때 Scene이 나오는건 현재상태에선 구현할 수 없어서 확인할 수가 없습니다)
![image](https://user-images.githubusercontent.com/87409148/159210483-abcd0708-004e-4362-85da-b9547e0cb997.png)

**Comment by sdkfile** [comment]
이거 닫을게요 그러면!
