### ISSUE TITLE
Sentry C SDK 붙여서 C 파트 Crash도 추적하기

### ISSUE THREAD

**Issue by sdkfile** [ACON3D/ABLER#94]
## 요약
C SDK를 또는 Sentry로 뭔가 내용을 날리는 함수를 블렌더 내 Crash signal handler에 붙여서 스택 트레이스와 함께 보내는 방법을 찾는중

## Sentry Native SDK Documentation
[링크](https://docs.sentry.io/platforms/native/)

## 기능을 집어넣어야 하는 부분 (Crash signal handler)
https://github.com/ACON3D/ABLER/blob/740be30baf72686a916aec22cbcbc35d754c981a/source/creator/creator_signals.c#L107-L199

**Comment by sdkfile** [comment]
이거는 너무 공수가 많이 들어서 필요성이 대두되기 전까지는 드롭하는게 좋을 것 같습니다...

**Comment by seungha-kim** [comment]
> 이거는 너무 공수가 많이 들어서 필요성이 대두되기 전까지는 드롭하는게 좋을 것 같습니다...

찬성임다!!!!!!!!!!!

**Comment by sdkfile** [comment]
이슈랑 PR 닫아놓을게용~
